### ISSUE TITLE
Feedback tests

### ISSUE THREAD

**Issue by matiaslopezd** [Krico16/backend-jr-hiring#11]
Hi @Krico16! I'm here to give my feedback on your test!

# Test 1 
Excellent :heavy_check_mark:

# Test 2

Suggestion: Catch correctly, maybe the response is not `JSON`, could be an error string from the database! This could finish on uncaught error = server goes down.
https://github.com/Krico16/backend-jr-hiring/blob/fb5502801f996ac4e60f2ca5a71e2e3b5db79311/test2.js#L6

# Test 3
Suggestion 1:

Here is better to use the conditional ternary operator.
https://github.com/Krico16/backend-jr-hiring/blob/fb5502801f996ac4e60f2ca5a71e2e3b5db79311/test3.js#L14

```js
return (Object.keys(result).length > 0) ? Array.from(result) : new NotFound();
```

Suggestion 2: 

Here apply all types of non-valid `id` like `null`, `undefined`, `""`, etc.
https://github.com/Krico16/backend-jr-hiring/blob/fb5502801f996ac4e60f2ca5a71e2e3b5db79311/test3.js#L18
```js
(!id) ? ..
```

Suggestion 3:

1. Don't need to use `if/else`.
https://github.com/Krico16/backend-jr-hiring/blob/fb5502801f996ac4e60f2ca5a71e2e3b5db79311/test3.js#L23
2. Never use `==` for comparison

3. Caution with `forEach`, you are iterating over all elements. Is completely inefficient! Remember you're on the server-side any unnecessary process needs to be refactored
https://github.com/Krico16/backend-jr-hiring/blob/fb5502801f996ac4e60f2ca5a71e2e3b5db79311/test3.js#L28
```js
async function updateOne(model, id, body) {

    if (!id) return new NotFound(`No data for update found with the id equal as "${id}".`);
    const data = this.db[model];

    const index = data.findIndex(element => element.id === id); // Stop to iterating when ids match, imagine 10M of data length using forEach... 😴
    data[index] = Object.assign(data[index], body);
    return data[index];
}
```

As a general suggestion, not use var on the server-side only use `let` and `const`.

Congrats! 🎊

**Comment by Krico16** [comment]
Thanks @matiaslopezd, I really appreciate your feedback 🤗
